# Generated by Django 2.2 on 2019-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepropertis',
            name='property_data',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='sitepropertis',
            name='property_name',
            field=models.CharField(max_length=60),
        ),
    ]
