# Generated by Django 2.2 on 2019-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staicsitecontent', '0003_auto_20190527_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/teachers', verbose_name='Загрузка изображения'),
        ),
    ]
