# Generated by Django 2.2 on 2019-05-27 09:57

from django.db import migrations, models
import staicsitecontent.models


class Migration(migrations.Migration):

    dependencies = [
        ('staicsitecontent', '0004_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to=staicsitecontent.models.UploadToPathAndRename('esz/media/img/teachers'), verbose_name='Загрузка изображения'),
        ),
    ]
