# Generated by Django 2.2 on 2019-05-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('Cat_Description', models.TextField(max_length=4096, verbose_name='Опиание категории')),
                ('Cat_photo', models.ImageField(upload_to='img', verbose_name='Загрузка изображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, verbose_name='Название центра')),
                ('ShortName', models.CharField(max_length=100, verbose_name='Краткое название центра')),
                ('Description', models.TextField(max_length=2048, verbose_name='Описание')),
                ('Code', models.CharField(max_length=30, verbose_name='Код')),
                ('Address', models.TextField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Центр',
                'verbose_name_plural': 'Центры',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договора',
            },
        ),
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationForm', models.CharField(max_length=100, verbose_name='Форма обучения')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Формы обучения',
            },
        ),
        migrations.CreateModel(
            name='EducationYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationYear', models.CharField(max_length=10, unique=True, verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'Год обучения',
                'verbose_name_plural': 'Годы обучения',
            },
        ),
        migrations.CreateModel(
            name='FinancingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30, verbose_name='Тип финансирования')),
            ],
            options={
                'verbose_name': 'Тип финансирования',
                'verbose_name_plural': 'Типы финансирования',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Наименование программы')),
                ('ShortName', models.CharField(max_length=30, verbose_name='Краткое название')),
                ('Description', models.TextField(verbose_name='Описание программы')),
                ('IdImage', models.IntegerField(null=True)),
                ('Code', models.CharField(max_length=30, verbose_name='Код программы')),
                ('Center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staicsitecontent.Center', verbose_name='Центр')),
                ('FinancingType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staicsitecontent.FinancingType', verbose_name='Тип финансирования')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('ProgramLeadsTeacher', models.ManyToManyField(to='staicsitecontent.Program', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Педагог',
                'verbose_name_plural': 'Педагоги',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Название группы')),
                ('ShortName', models.CharField(max_length=30, verbose_name='Короткое название группы')),
                ('Code', models.CharField(max_length=30, verbose_name='Код группы')),
                ('Center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staicsitecontent.Center', verbose_name='Центр')),
                ('Program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staicsitecontent.Program', verbose_name='Программа обучения')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staicsitecontent.Teacher', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Группа обучения',
                'verbose_name_plural': 'Группы обучения',
            },
        ),
    ]
