# Generated by Django 2.2 on 2019-05-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staicsitecontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('LastName', models.CharField(max_length=30, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('FullName', models.CharField(max_length=180, verbose_name='ФИО полностью')),
                ('ApplicantSnils', models.CharField(max_length=11, verbose_name='СНИЛС')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Дата договора')),
                ('Number', models.CharField(max_length=30, verbose_name='Номер договора')),
                ('LessonBeginDate', models.DateField(verbose_name='Дата начала занятий')),
                ('LessonEndDate', models.DateField(verbose_name='Дата окончания занятий')),
                ('MasteringProgramBeginDate', models.DateField(verbose_name='Дата начала под. занятий')),
                ('MasteringProgramEndDate', models.DateField(verbose_name='Дата окончания под. занятий')),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.Applicant', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'permissions': (('can_can', 'Can Do'),),
            },
        ),
        migrations.CreateModel(
            name='ContractSignTransactionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SatateLabel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=30)),
                ('RoleLabel', models.CharField(max_length=30)),
                ('RoleDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SendEmailTransactionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SatateLabel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SendSmsTransactionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SatateLabel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantEmails',
            fields=[
                ('Applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='suddop.Applicant', verbose_name='Заявитель')),
                ('Email', models.CharField(max_length=30, unique=True, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'Адрес электронной почты',
                'verbose_name_plural': 'Адреса электронной почты',
            },
        ),
        migrations.CreateModel(
            name='ApplicantPassport',
            fields=[
                ('Applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='suddop.Applicant', verbose_name='Заявитель')),
                ('ApplicantDocWhomWhenIssued', models.TextField(verbose_name='Кем и когда выдан')),
                ('ApplicantAddress', models.TextField(verbose_name='Адрес регистрации')),
                ('SerialPaspDoc', models.CharField(max_length=4, verbose_name='Серия')),
                ('NumPaspDoc', models.CharField(max_length=6, verbose_name='Номер')),
                ('DataOutDoc', models.DateField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Документ удостоверяющий личность',
                'verbose_name_plural': 'Документы удостоверяющие личность',
            },
        ),
        migrations.CreateModel(
            name='ApplicantPhones',
            fields=[
                ('Applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='suddop.Applicant', verbose_name='Заявитель')),
                ('Phone', models.CharField(max_length=30, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телефон заявителя',
                'verbose_name_plural': 'Телефоны заявителей',
            },
        ),
        migrations.CreateModel(
            name='ContractSign',
            fields=[
                ('SignKey', models.CharField(max_length=32, unique=True)),
                ('Contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='suddop.Contract', verbose_name='Договор')),
                ('SmsCode', models.CharField(max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Login', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=16)),
                ('Roles', models.ManyToManyField(to='suddop.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='ФИО (полностью)')),
                ('DateBirth', models.DateField(verbose_name='Дата рождения')),
                ('DocumentType', models.CharField(choices=[('M', 'Метрика'), ('S', 'СНИЛС'), ('-', 'Не определен')], default='-', max_length=1, null=True, verbose_name='Тип документа')),
                ('SeriaNumDoc', models.CharField(max_length=11, null=True, verbose_name='Номер')),
                ('DatarRegDoc', models.DateField(null=True, verbose_name='Дата регистрации')),
                ('GenderLabel', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('-', 'Не определен')], default='-', max_length=1, verbose_name='Пол')),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.Applicant', verbose_name='Законный представитель')),
                ('Group', models.ManyToManyField(to='staicsitecontent.Group', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
            },
        ),
        migrations.CreateModel(
            name='EmailTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.Contract', verbose_name='')),
                ('SendEmailTransactionState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.SendEmailTransactionState', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ContractSignTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.Contract', verbose_name='')),
                ('ContractSignTransactionState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.ContractSignTransactionState', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='ContractStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suddop.ContractStatus', verbose_name='Статус договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ContractType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staicsitecontent.ContractType', verbose_name='Тип договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='EducationForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staicsitecontent.EducationForm', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='EducationYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staicsitecontent.EducationYear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staicsitecontent.Program', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suddop.Student', verbose_name='Обучающийся'),
        ),
    ]
