# Generated by Django 2.2 on 2019-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suddop', '0004_auto_20190525_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuddopConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SConstName', models.CharField(max_length=30)),
                ('SConstValue', models.TextField()),
            ],
        ),
    ]
