# Generated by Django 2.2 on 2019-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suddop', '0005_suddopconstants'),
    ]

    operations = [
        migrations.AddField(
            model_name='suddopconstants',
            name='SConstDescription',
            field=models.TextField(default=''),
        ),
    ]
