# Generated by Django 2.2 on 2019-05-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suddop', '0006_suddopconstants_sconstdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GenderLabel',
            field=models.CharField(choices=[('Мужской', 'М'), ('Женский', 'Ж'), ('Не определен', '-')], default='-', max_length=15, verbose_name='Пол'),
        ),
    ]
